def uniform_layered_qasm(size: int, count: int) -> list[str]: ...
def uniform_layered_m_body(size: int, interaction: int) -> str: ...


def dist_select_m_body(size: int, interaction: int,
                       parallel_parameter: int) -> str: ...
